name: Test and benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  benchmark:
    name: Run C++ benchmark and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run benchmarks with Catch2
        run: |
          echo g++-v --version
          g++-10 -std=c++20 -o ./test/outcomeTests.o ./test/outcomeTests.cc
          ./test/outcomeTests.o
